// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class PAppSession;
@class PAppSessionBuilder;



@interface PappSessionRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PAppSession_sessionId @"sessionId"
#define PAppSession_realName @"realName"
#define PAppSession_userName @"userName"
#define PAppSession_userId @"userId"
#define PAppSession_secret @"secret"
#define PAppSession_signinDate @"signinDate"
#define PAppSession_profileImageUrl @"profileImageUrl"
#define PAppSession_appName @"appName"
#define PAppSession_deviceName @"deviceName"
#define PAppSession_deviceScreenSize @"deviceScreenSize"
#define PAppSession_osName @"osName"
#define PAppSession_osVersion @"osVersion"
#define PAppSession_packageVersion @"packageVersion"
#define PAppSession_packageName @"packageName"
#define PAppSession_deviceId @"deviceId"
#define PAppSession_deviceToken @"deviceToken"
#define PAppSession_apnsEnabled @"apnsEnabled"
#define PAppSession_latesAppVers @"latesAppVers"
#define PAppSession_localeIdentifier @"localeIdentifier"
#define PAppSession_latitude @"latitude"
#define PAppSession_longitude @"longitude"
#define PAppSession_cityId @"cityId"
#define PAppSession_userKind @"userKind"
#define PAppSession_userDemo @"userDemo"
@interface PAppSession : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasUserId_:1;
  BOOL hasApnsEnabled_:1;
  BOOL hasCityId_:1;
  BOOL hasUserKind_:1;
  BOOL hasUserDemo_:1;
  BOOL hasSessionId_:1;
  BOOL hasRealName_:1;
  BOOL hasUserName_:1;
  BOOL hasSecret_:1;
  BOOL hasSigninDate_:1;
  BOOL hasProfileImageUrl_:1;
  BOOL hasAppName_:1;
  BOOL hasDeviceName_:1;
  BOOL hasDeviceScreenSize_:1;
  BOOL hasOsName_:1;
  BOOL hasOsVersion_:1;
  BOOL hasPackageVersion_:1;
  BOOL hasPackageName_:1;
  BOOL hasDeviceId_:1;
  BOOL hasDeviceToken_:1;
  BOOL hasLatesAppVers_:1;
  BOOL hasLocaleIdentifier_:1;
  Float32 latitude;
  Float32 longitude;
  SInt64 userId;
  SInt32 apnsEnabled;
  SInt32 cityId;
  SInt32 userKind;
  SInt32 userDemo;
  NSString* sessionId;
  NSString* realName;
  NSString* userName;
  NSString* secret;
  NSString* signinDate;
  NSString* profileImageUrl;
  NSString* appName;
  NSString* deviceName;
  NSString* deviceScreenSize;
  NSString* osName;
  NSString* osVersion;
  NSString* packageVersion;
  NSString* packageName;
  NSString* deviceId;
  NSString* deviceToken;
  NSString* latesAppVers;
  NSString* localeIdentifier;
}
- (BOOL) hasSessionId;
- (BOOL) hasRealName;
- (BOOL) hasUserName;
- (BOOL) hasUserId;
- (BOOL) hasSecret;
- (BOOL) hasSigninDate;
- (BOOL) hasProfileImageUrl;
- (BOOL) hasAppName;
- (BOOL) hasDeviceName;
- (BOOL) hasDeviceScreenSize;
- (BOOL) hasOsName;
- (BOOL) hasOsVersion;
- (BOOL) hasPackageVersion;
- (BOOL) hasPackageName;
- (BOOL) hasDeviceId;
- (BOOL) hasDeviceToken;
- (BOOL) hasApnsEnabled;
- (BOOL) hasLatesAppVers;
- (BOOL) hasLocaleIdentifier;
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
- (BOOL) hasCityId;
- (BOOL) hasUserKind;
- (BOOL) hasUserDemo;
@property (readonly, strong) NSString* sessionId;
@property (readonly, strong) NSString* realName;
@property (readonly, strong) NSString* userName;
@property (readonly) SInt64 userId;
@property (readonly, strong) NSString* secret;
@property (readonly, strong) NSString* signinDate;
@property (readonly, strong) NSString* profileImageUrl;
@property (readonly, strong) NSString* appName;
@property (readonly, strong) NSString* deviceName;
@property (readonly, strong) NSString* deviceScreenSize;
@property (readonly, strong) NSString* osName;
@property (readonly, strong) NSString* osVersion;
@property (readonly, strong) NSString* packageVersion;
@property (readonly, strong) NSString* packageName;
@property (readonly, strong) NSString* deviceId;
@property (readonly, strong) NSString* deviceToken;
@property (readonly) SInt32 apnsEnabled;
@property (readonly, strong) NSString* latesAppVers;
@property (readonly, strong) NSString* localeIdentifier;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longitude;
@property (readonly) SInt32 cityId;
@property (readonly) SInt32 userKind;
@property (readonly) SInt32 userDemo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PAppSessionBuilder*) builder;
+ (PAppSessionBuilder*) builder;
+ (PAppSessionBuilder*) builderWithPrototype:(PAppSession*) prototype;
- (PAppSessionBuilder*) toBuilder;

+ (PAppSession*) parseFromData:(NSData*) data;
+ (PAppSession*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PAppSession*) parseFromInputStream:(NSInputStream*) input;
+ (PAppSession*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PAppSession*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PAppSession*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PAppSessionBuilder : PBGeneratedMessageBuilder {
@private
  PAppSession* resultPappSession;
}

- (PAppSession*) defaultInstance;

- (PAppSessionBuilder*) clear;
- (PAppSessionBuilder*) clone;

- (PAppSession*) build;
- (PAppSession*) buildPartial;

- (PAppSessionBuilder*) mergeFrom:(PAppSession*) other;
- (PAppSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PAppSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (PAppSessionBuilder*) setSessionId:(NSString*) value;
- (PAppSessionBuilder*) clearSessionId;

- (BOOL) hasRealName;
- (NSString*) realName;
- (PAppSessionBuilder*) setRealName:(NSString*) value;
- (PAppSessionBuilder*) clearRealName;

- (BOOL) hasUserName;
- (NSString*) userName;
- (PAppSessionBuilder*) setUserName:(NSString*) value;
- (PAppSessionBuilder*) clearUserName;

- (BOOL) hasUserId;
- (SInt64) userId;
- (PAppSessionBuilder*) setUserId:(SInt64) value;
- (PAppSessionBuilder*) clearUserId;

- (BOOL) hasSecret;
- (NSString*) secret;
- (PAppSessionBuilder*) setSecret:(NSString*) value;
- (PAppSessionBuilder*) clearSecret;

- (BOOL) hasSigninDate;
- (NSString*) signinDate;
- (PAppSessionBuilder*) setSigninDate:(NSString*) value;
- (PAppSessionBuilder*) clearSigninDate;

- (BOOL) hasProfileImageUrl;
- (NSString*) profileImageUrl;
- (PAppSessionBuilder*) setProfileImageUrl:(NSString*) value;
- (PAppSessionBuilder*) clearProfileImageUrl;

- (BOOL) hasAppName;
- (NSString*) appName;
- (PAppSessionBuilder*) setAppName:(NSString*) value;
- (PAppSessionBuilder*) clearAppName;

- (BOOL) hasDeviceName;
- (NSString*) deviceName;
- (PAppSessionBuilder*) setDeviceName:(NSString*) value;
- (PAppSessionBuilder*) clearDeviceName;

- (BOOL) hasDeviceScreenSize;
- (NSString*) deviceScreenSize;
- (PAppSessionBuilder*) setDeviceScreenSize:(NSString*) value;
- (PAppSessionBuilder*) clearDeviceScreenSize;

- (BOOL) hasOsName;
- (NSString*) osName;
- (PAppSessionBuilder*) setOsName:(NSString*) value;
- (PAppSessionBuilder*) clearOsName;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (PAppSessionBuilder*) setOsVersion:(NSString*) value;
- (PAppSessionBuilder*) clearOsVersion;

- (BOOL) hasPackageVersion;
- (NSString*) packageVersion;
- (PAppSessionBuilder*) setPackageVersion:(NSString*) value;
- (PAppSessionBuilder*) clearPackageVersion;

- (BOOL) hasPackageName;
- (NSString*) packageName;
- (PAppSessionBuilder*) setPackageName:(NSString*) value;
- (PAppSessionBuilder*) clearPackageName;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (PAppSessionBuilder*) setDeviceId:(NSString*) value;
- (PAppSessionBuilder*) clearDeviceId;

- (BOOL) hasDeviceToken;
- (NSString*) deviceToken;
- (PAppSessionBuilder*) setDeviceToken:(NSString*) value;
- (PAppSessionBuilder*) clearDeviceToken;

- (BOOL) hasApnsEnabled;
- (SInt32) apnsEnabled;
- (PAppSessionBuilder*) setApnsEnabled:(SInt32) value;
- (PAppSessionBuilder*) clearApnsEnabled;

- (BOOL) hasLatesAppVers;
- (NSString*) latesAppVers;
- (PAppSessionBuilder*) setLatesAppVers:(NSString*) value;
- (PAppSessionBuilder*) clearLatesAppVers;

- (BOOL) hasLocaleIdentifier;
- (NSString*) localeIdentifier;
- (PAppSessionBuilder*) setLocaleIdentifier:(NSString*) value;
- (PAppSessionBuilder*) clearLocaleIdentifier;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (PAppSessionBuilder*) setLatitude:(Float32) value;
- (PAppSessionBuilder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float32) longitude;
- (PAppSessionBuilder*) setLongitude:(Float32) value;
- (PAppSessionBuilder*) clearLongitude;

- (BOOL) hasCityId;
- (SInt32) cityId;
- (PAppSessionBuilder*) setCityId:(SInt32) value;
- (PAppSessionBuilder*) clearCityId;

- (BOOL) hasUserKind;
- (SInt32) userKind;
- (PAppSessionBuilder*) setUserKind:(SInt32) value;
- (PAppSessionBuilder*) clearUserKind;

- (BOOL) hasUserDemo;
- (SInt32) userDemo;
- (PAppSessionBuilder*) setUserDemo:(SInt32) value;
- (PAppSessionBuilder*) clearUserDemo;
@end


// @@protoc_insertion_point(global_scope)
