// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class PAppResponse;
@class PAppResponseBuilder;



@interface PappResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PAppResponse_msg @"msg"
#define PAppResponse_sessionId @"sessionId"
#define PAppResponse_version @"version"
#define PAppResponse_code @"code"
#define PAppResponse_total @"total"
#define PAppResponse_data @"data"
#define PAppResponse_errors @"errors"
@interface PAppResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasVersion_:1;
  BOOL hasCode_:1;
  BOOL hasTotal_:1;
  BOOL hasMsg_:1;
  BOOL hasSessionId_:1;
  SInt32 version;
  SInt32 code;
  SInt32 total;
  NSString* msg;
  NSString* sessionId;
  NSMutableArray * errorsArray;
  NSMutableArray * dataArray;
}
- (BOOL) hasMsg;
- (BOOL) hasSessionId;
- (BOOL) hasVersion;
- (BOOL) hasCode;
- (BOOL) hasTotal;
@property (readonly, strong) NSString* msg;
@property (readonly, strong) NSString* sessionId;
@property (readonly) SInt32 version;
@property (readonly) SInt32 code;
@property (readonly) SInt32 total;
@property (readonly, strong) NSArray * data;
@property (readonly, strong) NSArray * errors;
- (NSData*)dataAtIndex:(NSUInteger)index;
- (NSString*)errorsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PAppResponseBuilder*) builder;
+ (PAppResponseBuilder*) builder;
+ (PAppResponseBuilder*) builderWithPrototype:(PAppResponse*) prototype;
- (PAppResponseBuilder*) toBuilder;

+ (PAppResponse*) parseFromData:(NSData*) data;
+ (PAppResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PAppResponse*) parseFromInputStream:(NSInputStream*) input;
+ (PAppResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PAppResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PAppResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PAppResponseBuilder : PBGeneratedMessageBuilder {
@private
  PAppResponse* resultPappResponse;
}

- (PAppResponse*) defaultInstance;

- (PAppResponseBuilder*) clear;
- (PAppResponseBuilder*) clone;

- (PAppResponse*) build;
- (PAppResponse*) buildPartial;

- (PAppResponseBuilder*) mergeFrom:(PAppResponse*) other;
- (PAppResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PAppResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsg;
- (NSString*) msg;
- (PAppResponseBuilder*) setMsg:(NSString*) value;
- (PAppResponseBuilder*) clearMsg;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (PAppResponseBuilder*) setSessionId:(NSString*) value;
- (PAppResponseBuilder*) clearSessionId;

- (BOOL) hasVersion;
- (SInt32) version;
- (PAppResponseBuilder*) setVersion:(SInt32) value;
- (PAppResponseBuilder*) clearVersion;

- (BOOL) hasCode;
- (SInt32) code;
- (PAppResponseBuilder*) setCode:(SInt32) value;
- (PAppResponseBuilder*) clearCode;

- (BOOL) hasTotal;
- (SInt32) total;
- (PAppResponseBuilder*) setTotal:(SInt32) value;
- (PAppResponseBuilder*) clearTotal;

- (NSMutableArray *)data;
- (NSData*)dataAtIndex:(NSUInteger)index;
- (PAppResponseBuilder *)addData:(NSData*)value;
- (PAppResponseBuilder *)setDataArray:(NSArray *)array;
- (PAppResponseBuilder *)clearData;

- (NSMutableArray *)errors;
- (NSString*)errorsAtIndex:(NSUInteger)index;
- (PAppResponseBuilder *)addErrors:(NSString*)value;
- (PAppResponseBuilder *)setErrorsArray:(NSArray *)array;
- (PAppResponseBuilder *)clearErrors;
@end


// @@protoc_insertion_point(global_scope)
