source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iOSBootstrap_Example', :exclusive => true do
  pod "iOSBootstrap", :path => "../"
end

target 'iOSBootstrap_Tests', :exclusive => true do
  pod "iOSBootstrap", :path => "../"

  
end
